### ISSUE TITLE
Switch the default git branch from master to main

### ISSUE THREAD

**Issue by oliverklee** [lwe/page_title_helper#115]
We shouldn't use branch names that have racist connotations anymore.

https://stevenmortimer.com/5-steps-to-change-github-default-branch-from-master-to-main/

**Comment by lwe** [comment]
Sure, good point, thanks! 👍

**Comment by lwe** [comment]
Done, thanks for the input @oliverklee

**Comment by oliverklee** [comment]
@lwe Thanks!
