### ISSUE TITLE
Release version 5.0.0

### ISSUE THREAD

**Issue by oliverklee** [lwe/page_title_helper#125]
@lwe Should we have a 5.0.0 release (after #124 is merged)?

**Comment by lwe** [comment]
Yes, sure, I think also worth trying to new pipeline, isn't it?

**Comment by oliverklee** [comment]
> Yes, sure, I think also worth trying to new pipeline, isn't it?

Definitely.

**Comment by oliverklee** [comment]
@lwe Will you take care of doing the release?

**Comment by lwe** [comment]
No, please, your honor @oliverklee 👍 Go ahead and create the tag!

**Comment by oliverklee** [comment]
Done:
- https://github.com/lwe/page_title_helper/releases/tag/v5.0.0
- https://rubygems.org/gems/page_title_helper/versions/5.0.0

**Comment by lwe** [comment]
Awesome, thanks a lot.
