### ISSUE TITLE
Compatibility with Rails 8.0

### ISSUE THREAD

**Issue by jetienne** [lwe/page_title_helper#199]
Hi!

The current stable version of PageTitleHelper doesn't seem to be compatible with Rails 8.0, since it requires at most Rails version 7.3.

Do you plan to release a new version soon?

**Comment by oliverklee** [comment]
Hi @jetienne, I have just released version 9.0.0 that supports Rails 8.0:
https://github.com/lwe/page_title_helper/releases/tag/v9.0.0
https://rubygems.org/gems/page_title_helper
