### ISSUE TITLE
Drop support for Rails 3.2?

### ISSUE THREAD

**Issue by lwe** [lwe/page_title_helper#26]
Added Ruby 2.2 to the test matrix on travis and failed on Rails 3.2, personally I'd be happy to sunset support for 3.2. In the meantime I've marked the 3.2 gemfile as _allowed to fail_.

What do yo think?

**Comment by oliverklee** [comment]
I have created issue #25 for this. I propose we drop support for 3.2 once it is end-of-lifed, i.e., it does not get critical security updated anymore (which is after Rails 5.0 has been released).

**Comment by oliverklee** [comment]
@lwe Would this  play be okay for you?

**Comment by lwe** [comment]
Works for me!
