### ISSUE TITLE
Make basename customizable

### ISSUE THREAD

**Issue by jmuheim** [lwe/page_title_helper#34]

**Comment by lwe** [comment]
It probably should make use of `Rails.application.class.parent_name.humanize` instead

**Comment by jmuheim** [comment]
I think it should use `Rails.application.class.parent_name.humanize` by default and allow to be overridden by setting an `en.application_name` or something.

**Comment by lwe** [comment]
It already can be overriden using translations: `app.name`

**Comment by jmuheim** [comment]
Thanks!
