### ISSUE TITLE
Add a Code of Conduct

### ISSUE THREAD

**Issue by oliverklee** [lwe/page_title_helper#37]
Like this one: https://github.com/jjriv/emogrifier/blob/master/CODE_OF_CONDUCT.md

**Comment by oliverklee** [comment]
@lwe: Which email address should we use as contact for the CoC?

**Comment by lwe** [comment]
Is there an e-mail address required?

**Comment by oliverklee** [comment]
Yes, in the section "enforcement", there should be an email address that an be contacted if someone would like to report harassment or any other violation.

**Comment by lwe** [comment]
Use lukas dot westermann at gmail dot com, thanks
