### ISSUE TITLE
gemfiles/Gemfile.* are included in the gem

### ISSUE THREAD

**Issue by oliverklee** [lwe/page_title_helper#80]
It looks like the Gemfiles in gemflies/ get included in the gem because they match the pattern "Gemfile" in the gemspec in the "files" section.

Should we rename those files, e.g., from "Gemfile.*" to "gemfiles.*"?

**Comment by lwe** [comment]
Instead maybe change the inclusion rules of what gets included into the gem, personally I rather like that these have a similar name.

**Comment by oliverklee** [comment]
Well, the inclusion rule must include "Gemfile" so the "normal" Gemfile gets included. Maybe we can use a regular expression there?

**Comment by oliverklee** [comment]
This is not an issue anymore. Closing.
