### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by cacquani** [lwe/page_title_helper#85]
Hi, I just wanted to ask if you have any roadmap for a new release?

I ask because the last one is from 2012 and you have added and improved a lot since then, but without a 'proper' release it's not possible to include the latest improvements into another gem.

Thanks in advance for your answer :)

**Comment by lwe** [comment]
Good morning. That is true, if anyone is interested in maintaining this, will update the readme to reflect that I’m looking for a maintainer.

Thanks for the input

**Comment by lwe** [comment]
^^ say hello to version 3.0.0, with support for Rails 4.2 and 5.x. Have fun and nice Sunday. Big thanks to @oliverklee for making this possible.

https://rubygems.org/gems/page_title_helper
