### ISSUE TITLE
Release 4.0.0

### ISSUE THREAD

**Issue by oliverklee** [lwe/page_title_helper#97]
Please let's have a (breaking) 4.0.0 release soon so people with Rails 6 can use the Gem. :heart:

**Comment by lwe** [comment]
Works for me. Should I ship it today?

**Comment by lwe** [comment]
@oliverklee, anything left required for this to happen?

**Comment by oliverklee** [comment]
These are the release steps I see:
- update the changelog to add empty headings for the next release and remove empty sub-headings for 3.0.0, and remove the Rails version numbers from the README and make sure the version number in the code is correct
- create a new tag and add release notes to GitHub
- publish the new version on RubyGems

Apart from that, everythings is ready to release as far as I can see.

**Comment by lwe** [comment]
@oliverklee, working on publishing, additionally, I did add you as owner of `page_title_helper`.

**Comment by lwe** [comment]
...and 4.0 is published. Have fun y'all
