### ISSUE TITLE
Fix parameter issue with latest Ruby

### ISSUE THREAD

**Issue by oliverklee** [lwe/page_title_helper#99]
https://travis-ci.org/lwe/page_title_helper/jobs/591079509

ultipleFormatsTest#test_: #page_title supporting multiple formats through arrays should accept an array passed in the page_title block and use the second argument as format. :

FrozenError: can't modify frozen String: "default_static_extension"

**Comment by oliverklee** [comment]
I've found a blog post that might help with the first issue.
https://eregon.me/blog/2019/11/10/the-delegation-challenge-of-ruby27.html

**Comment by lwe** [comment]
Thank you, can you fix this somehow?

**Comment by oliverklee** [comment]
I hope so. :-) I'll do it when I find the time.

**Comment by lwe** [comment]
Haha, thanks a lot @oliverklee! :)

**Comment by oliverklee** [comment]
This is not an issue anymore. Closing.
